# Generated by Django 3.0.5 on 2022-02-06 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20220206_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='userprofile'),
        ),
        migrations.AlterField(
            model_name='account',
            name='code',
            field=models.CharField(blank=True, default='CITKWQRC', max_length=8, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
